# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.27)
{
  
  description = "Modern C";

  
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*";
  };

  
  outputs = { self, flake-schemas, nixpkgs }:
    let
      
      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {
      
      schemas = flake-schemas.schemas;

      
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          buildInputs = with pkgs; [
            vulkan-headers
            vulkan-loader
            vulkan-validation-layers
            vulkan-tools
            vulkan-tools-lunarg
            vulkan-utility-libraries
            vulkan-extension-layer
            vulkan-validation-layers
            vulkan-volk
            spirv-headers
            spirv-tools
            spirv-cross
            glslang

            sdl3
            libplacebo
            pkg-config
          ];
          
          packages = with pkgs; [
            gcc
            clang
            clang-tools
            just
          ];
        };
      });
    };
}
